//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insite.WIS.DistributorDataSolutions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DDSDataFeedProductSourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DDSDataFeedProductSourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insite.WIS.DistributorDataSolutions.Resources.DDSDataFeedProductSourceFile", typeof(DDSDataFeedProductSourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category_codes.{0}.{1}.code.
        /// </summary>
        internal static string CategoryCodeColumnFormat {
            get {
                return ResourceManager.GetString("CategoryCodeColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category_codes..
        /// </summary>
        internal static string CategoryColumnPrefix {
            get {
                return ResourceManager.GetString("CategoryColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distributor_product_id.
        /// </summary>
        internal static string DistributorProductIdColumn {
            get {
                return ResourceManager.GetString("DistributorProductIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facets..
        /// </summary>
        internal static string FacetColumnPrefix {
            get {
                return ResourceManager.GetString("FacetColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facets.{0}.name.
        /// </summary>
        internal static string FacetNameColumnFormat {
            get {
                return ResourceManager.GetString("FacetNameColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facets.{0}.values.{1}.value.
        /// </summary>
        internal static string FacetValueColumnFormat {
            get {
                return ResourceManager.GetString("FacetValueColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images..
        /// </summary>
        internal static string ImageColumnPrefix {
            get {
                return ResourceManager.GetString("ImageColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.{0}.name.
        /// </summary>
        internal static string ImageNameColumnFormat {
            get {
                return ResourceManager.GetString("ImageNameColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.{0}.uri_large.
        /// </summary>
        internal static string ImageUriLargeColumnFormat {
            get {
                return ResourceManager.GetString("ImageUriLargeColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.{0}.uri_medium.
        /// </summary>
        internal static string ImageUriMediumColumnFormat {
            get {
                return ResourceManager.GetString("ImageUriMediumColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.{0}.uri_small.
        /// </summary>
        internal static string ImageUriSmallColumnFormat {
            get {
                return ResourceManager.GetString("ImageUriSmallColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.{0}.uri_thumb.
        /// </summary>
        internal static string ImageUriThumbColumnFormat {
            get {
                return ResourceManager.GetString("ImageUriThumbColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sections..
        /// </summary>
        internal static string SectionColumnPrefix {
            get {
                return ResourceManager.GetString("SectionColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uri_large.
        /// </summary>
        internal static string UriLargeColumn {
            get {
                return ResourceManager.GetString("UriLargeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uri_medium.
        /// </summary>
        internal static string UriMediumColumn {
            get {
                return ResourceManager.GetString("UriMediumColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uri_small.
        /// </summary>
        internal static string UriSmallColumn {
            get {
                return ResourceManager.GetString("UriSmallColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uri_thumb.
        /// </summary>
        internal static string UriThumbColumn {
            get {
                return ResourceManager.GetString("UriThumbColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string ValueColumn {
            get {
                return ResourceManager.GetString("ValueColumn", resourceCulture);
            }
        }
    }
}
