
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Prophet21.V2017.Middleware.Models.GetMyAccountOpenAR;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "GetMyAccountOpenAR", Namespace = "")]
public class GetMyAccountOpenAR
{
    public Request Request { get; set; }

    public Reply Reply { get; set; }

    public ReplyStatus ReplyStatus { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
public class Request
{
    public RequestB2BSellerVersion B2BSellerVersion { get; set; }

    public string CustomerCode { get; set; }

    public string StoreName { get; set; }

    public string WebReferenceNumber { get; set; }

    public int PageSize { get; set; }

    public string StartRowID { get; set; }

    public string GetTableOfContents { get; set; }

    public List<RequestSortColumn> ListOfSortColumns { get; set; } = new List<RequestSortColumn>();

    public string StartInvoiceNumber { get; set; }

    public string EndInvoiceNumber { get; set; }

    public string StartInvoiceDate { get; set; }

    public string EndInvoiceDate { get; set; }

    public string ShipToID { get; set; }

    public string AgingBasis { get; set; }

    public string GetCreditInvoices { get; set; }

    public string IncludePassThroughItems { get; set; }

    public string WebShopperId { get; set; }

    public string WebShopperEmailAddress { get; set; }

    public string RestrictDataByShopper { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "B2BSellerVersion", Namespace = "Request")]
public class RequestB2BSellerVersion
{
    public string MajorVersion { get; set; }

    public string MinorVersion { get; set; }

    public string BuildNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SortColumn", Namespace = "Request")]
public class RequestSortColumn
{
    [System.Xml.Serialization.XmlAttributeAttribute]
    public string Direction { get; set; }

    [System.Xml.Serialization.XmlTextAttribute]
    public string Value { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Reply", Namespace = "")]
public class Reply
{
    public List<ReplyOpenAR> ListOfOpenAR { get; set; } = new List<ReplyOpenAR>();

    public ReplyAgedAR AgedAR { get; set; }

    public int RowCount { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OpenAR", Namespace = "")]
public class ReplyOpenAR
{
    public string InvoiceNumber { get; set; }

    public string OpenInvoiceDate { get; set; }

    public string ARDescription { get; set; }

    public string ARDiscountDate { get; set; }

    public string ARDueDate { get; set; }

    public string ARAmountTotalSales { get; set; }

    public string ARAmountOpen { get; set; }

    public string PONumber { get; set; }

    public ReplyShipToAddress ShipToAddress { get; set; }

    public string WebShopperId { get; set; }

    public string WebShopperEmailAddress { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ShipToAddress", Namespace = "")]
public class ReplyShipToAddress
{
    public string ShipToID { get; set; }

    public string ShipToCompanyName { get; set; }

    public string ShipToAddress1 { get; set; }

    public string ShipToAddress2 { get; set; }

    public string ShipToAddress3 { get; set; }

    public string ShipToCity { get; set; }

    public string ShipToState { get; set; }

    public string ShipToZip { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "AgedAR", Namespace = "")]
public class ReplyAgedAR
{
    public decimal CurrentAmount { get; set; }

    public decimal Age1Amount { get; set; }

    public decimal Age1ToAge2Amount { get; set; }

    public decimal Age2ToAge3Amount { get; set; }

    public decimal OverAge3Amount { get; set; }

    public decimal TotalARAmountOpen { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ReplyStatus", Namespace = "")]
public class ReplyStatus
{
    public int Result { get; set; }

    public string Message { get; set; }
}