//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insite.WIS.Acumatica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PricingRefreshAcumaticaSourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PricingRefreshAcumaticaSourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insite.WIS.Acumatica.Resources.PricingRefreshAcumaticaSourceFile", typeof(PricingRefreshAcumaticaSourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string BasePriceType {
            get {
                return ResourceManager.GetString("BasePriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakQty.
        /// </summary>
        internal static string BreakQtyColumn {
            get {
                return ResourceManager.GetString("BreakQtyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CurrencyColumn {
            get {
                return ResourceManager.GetString("CurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CustomerColumn {
            get {
                return ResourceManager.GetString("CustomerColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerPriceClass.
        /// </summary>
        internal static string CustomerPriceClassColumn {
            get {
                return ResourceManager.GetString("CustomerPriceClassColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultPrice.
        /// </summary>
        internal static string DefaultPriceColumn {
            get {
                return ResourceManager.GetString("DefaultPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDate.
        /// </summary>
        internal static string EffectiveDateColumn {
            get {
                return ResourceManager.GetString("EffectiveDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpirationDate.
        /// </summary>
        internal static string ExpirationDateColumn {
            get {
                return ResourceManager.GetString("ExpirationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryID.
        /// </summary>
        internal static string InventoryIdColumn {
            get {
                return ResourceManager.GetString("InventoryIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceColumn {
            get {
                return ResourceManager.GetString("PriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceType.
        /// </summary>
        internal static string PriceTypeColumn {
            get {
                return ResourceManager.GetString("PriceTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/Customer Class.
        /// </summary>
        internal static string ProductCustomerClassPriceType {
            get {
                return ResourceManager.GetString("ProductCustomerClassPriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product/Customer.
        /// </summary>
        internal static string ProductCustomerPriceType {
            get {
                return ResourceManager.GetString("ProductCustomerPriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ProductPriceType {
            get {
                return ResourceManager.GetString("ProductPriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string PromotionColumn {
            get {
                return ResourceManager.GetString("PromotionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        internal static string UomColumn {
            get {
                return ResourceManager.GetString("UomColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string WarehouseColumn {
            get {
                return ResourceManager.GetString("WarehouseColumn", resourceCulture);
            }
        }
    }
}
