// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.CloudSuiteDistribution.V11.IonApi.Models.SfCustomerSummary
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class SfCustomerSummaryResponse
    {
        [JsonProperty("response")]
        public Response Response { get; set; }
    }

    public class Response
    {
        [JsonProperty("cErrorMessage")]
        public string ErrorMessage { get; set; }

        [JsonProperty("tCustsummary")]
        public CustomerSummaryCollection CustomerSummaryCollection { get; set; }
    }

    public class CustomerSummaryCollection
    {
        [JsonProperty("t-custsummary")]
        public List<CustomerSummary> CustomerSummaries { get; set; } = new List<CustomerSummary>();
    }

    public class CustomerSummary
    {
        [JsonProperty("Custname")]
        public string CustName { get; set; }

        public string Addr1 { get; set; }

        public string Addr2 { get; set; }

        public string Addr3 { get; set; }

        public string Addr4 { get; set; }

        public string City { get; set; }

        public string State { get; set; }

        [JsonProperty("Countrycd")]
        public string CountryCd { get; set; }

        [JsonProperty("Zipcd")]
        public string ZipCd { get; set; }

        [JsonProperty("Openordamt")]
        public decimal? OpenOrdAmt { get; set; }

        [JsonProperty("Billprdamt")]
        public decimal? BillPrdAmt { get; set; }

        [JsonProperty("Ageprd1")]
        public decimal? AgePrd1 { get; set; }

        [JsonProperty("Ageprd2")]
        public decimal? AgePrd2 { get; set; }

        [JsonProperty("Ageprd3")]
        public decimal? AgePrd3 { get; set; }

        [JsonProperty("Ageprd4")]
        public decimal? AgePrd4 { get; set; }

        [JsonProperty("Amtdue")]
        public decimal? AmtDue { get; set; }

        [JsonProperty("Futureamt")]
        public decimal? FutureAmt { get; set; }

        [JsonProperty("SalesMTD")]
        public decimal? SalesMtd { get; set; }

        [JsonProperty("SalesYTD")]
        public decimal? SalesYtd { get; set; }

        [JsonProperty("SalesLYTD")]
        public decimal? SalesLYtd { get; set; }

        [JsonProperty("Lastpaydt")]
        public DateTime? LastPayDt { get; set; }

        [JsonProperty("Firstsaledt")]
        public DateTime? FirstSaleDt { get; set; }

        [JsonProperty("Lastsaledt")]
        public DateTime? LastSaleDt { get; set; }

        [JsonProperty("Currencycd")]
        public string CurrencyCd { get; set; }

        [JsonProperty("Tradeopenordamt")]
        public decimal? TradeOpenOrdAmt { get; set; }

        [JsonProperty("Tradebillprdamt")]
        public decimal? TradeBillPrdAmt { get; set; }

        [JsonProperty("Tradeageprd1")]
        public decimal? TradeAgePrd1 { get; set; }

        [JsonProperty("Tradeageprd2")]
        public decimal? TradeAgePrd2 { get; set; }

        [JsonProperty("Tradeageprd3")]
        public decimal? TradeAgePrd3 { get; set; }

        [JsonProperty("Tradeageprd4")]
        public decimal? TradeAgePrd4 { get; set; }

        [JsonProperty("Tradeamtdue")]
        public decimal? TradeAmtDue { get; set; }

        [JsonProperty("Tradefutureamt")]
        public decimal? TradeFutureAmt { get; set; }

        [JsonProperty("TradesalesMTD")]
        public decimal? TradeSalesMtd { get; set; }

        [JsonProperty("TradesalesYTD")]
        public decimal? TradeSalesYtd { get; set; }

        [JsonProperty("TradesalesLYTD")]
        public decimal? TradeSalesLYtd { get; set; }

        [JsonProperty("Tradecurrencycd")]
        public string TradeCurrencyCd { get; set; }

        [JsonProperty("Termsdesc")]
        public string TermsDesc { get; set; }

        [JsonProperty("Agedaysper1")]
        public decimal? AgeDaysPer1 { get; set; }

        [JsonProperty("Agedaysper2")]
        public decimal? AgeDaysPer2 { get; set; }

        [JsonProperty("Agedaysper3")]
        public decimal? AgeDaysPer3 { get; set; }

        [JsonProperty("Agedaysper4")]
        public decimal? AgeDaysPer4 { get; set; }
    }
}
