// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.CloudSuiteDistribution.V11.IonApi.Models.SfCustomerSummary
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Serialization;

    public class SfCustomerSummaryRequest
    {
        [JsonProperty("request")]
        public Request Request { get; set; }
    }

    public class Request
    {
        public int CompanyNumber { get; set; }

        public string OperatorInit { get; set; }

        public string OperatorPassword { get; set; }

        public string CustomerNumber { get; set; }
    }
}
