
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V11.IonApi.Models.SFCustomerSummary;

using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

[System.SerializableAttribute]
public class SFCustomerSummaryRequest
{
    [JsonProperty("request")]
    public Request Request { get; set; }
}

[System.SerializableAttribute]
public class Request : IRequest
{
    public int CompanyNumber { get; set; }

    public string OperatorInit { get; set; }

    public string OperatorPassword { get; set; }

    public long CustomerNumber { get; set; }
}