// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Acumatica.V18.RestApi.Models.CustomerPaymentMethod
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class CustomerPaymentMethod
    {
        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public bool Active { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string CardAccountNbr { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string CashAccount { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public DateTime? CreatedDateTime { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string CustomerID { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string CustomerProfileID { get; set; }

        public List<Detail> Details { get; set; } = new List<Detail>();

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public int InstanceID { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public DateTime? LastModifiedDateTime { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string PaymentMethod { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string ProcCenterID { get; set; }
    }

    public class Detail
    {
        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string Name { get; set; }

        [JsonConverter(typeof(ValuePropertyJsonConverter))]
        public string Value { get; set; }
    }
}
