
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V10.SXApi.Models.OEPricingMultipleV4;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.OEPricingMultiple" + "V4")]
public class OEPricingMultipleV4Request
{
    public bool CheckOtherWhseInventory { get; set; }

    public decimal CustomerNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string EdiPartnerCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ExtraData { get; set; }

    public bool GetPriceBreaks { get; set; }

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Inproduct3> Inproduct { get; set; } = new List<Inproduct3>();

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string KeyCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string PricingMethod { get; set; }

    public bool SendFullQtyOnOrder { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipTo { get; set; }

    public bool UseDefaultWhse { get; set; }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2046.0")]
[System.SerializableAttribute]
[System.Diagnostics.DebuggerStepThroughAttribute]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Inproduct", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.OEPricingMultiple" + "V4")]
public class Inproduct3
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ExtraData { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string OperatorChannel { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ProductCode { get; set; }

    public decimal Quantity { get; set; }

    public int SequenceNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string UnitOfMeasure { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User3 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User4 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User5 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Warehouse { get; set; }
}