
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V10.SXApi.Models.OEPricingMultipleV4;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.OEPricingMultiple" + "V4")]
public class OEPricingMultipleV4Response
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ErrorMessage { get; set; }

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Outprice3> Outprice { get; set; } = new List<Outprice3>();

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Outpricebreak3> Outpricebreak { get; set; } = new List<Outpricebreak3>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Outprice", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.OEPricingMultiple" + "V4")]
public class Outprice3
{
    public decimal Commission { get; set; }

    public decimal DiscountAmount { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string DiscountType { get; set; }

    public System.DateTime DueDate { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ErrorMessage { get; set; }

    public decimal ExtendedAmount { get; set; }

    public decimal ExtendedDiscountAmount { get; set; }

    public decimal FreightAmount { get; set; }

    public bool FreightDiscountFlag { get; set; }

    public bool InventoryInOtherWhse { get; set; }

    public decimal NetAvailable { get; set; }

    public decimal Price { get; set; }

    public bool PriceBreaksExist { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string PriceCostPer { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string PriceOriginCode { get; set; }

    public int PricingRecordNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ProductCode { get; set; }

    public bool PromotionalFlag { get; set; }

    public decimal Quantity { get; set; }

    public decimal QuantityOnOrder { get; set; }

    public int SequenceNumber { get; set; }

    public int SpecialConversion { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string SpecialCostType { get; set; }

    public int SpeicalCostRecordNumber { get; set; }

    public decimal SpiffAmount { get; set; }

    public decimal StockingQuantity { get; set; }

    public decimal UnitConversion { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string UnitOfMeasure { get; set; }

    public decimal UnitsPerStocking { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string UnitsPerStockingText { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User3 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User4 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User5 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Warehouse { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Outpricebreak", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.OEPricingMultiple" + "V4")]
public class Outpricebreak3
{
    public decimal DiscountPercent1 { get; set; }

    public decimal DiscountPercent2 { get; set; }

    public decimal DiscountPercent3 { get; set; }

    public decimal DiscountPercent4 { get; set; }

    public decimal DiscountPercent5 { get; set; }

    public decimal DiscountPercent6 { get; set; }

    public decimal DiscountPercent7 { get; set; }

    public decimal DiscountPercent8 { get; set; }

    public decimal DiscountPercent9 { get; set; }

    public decimal PriceBreak1 { get; set; }

    public decimal PriceBreak2 { get; set; }

    public decimal PriceBreak3 { get; set; }

    public decimal PriceBreak4 { get; set; }

    public decimal PriceBreak5 { get; set; }

    public decimal PriceBreak6 { get; set; }

    public decimal PriceBreak7 { get; set; }

    public decimal PriceBreak8 { get; set; }

    public decimal PriceBreak9 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ProductCode { get; set; }

    public decimal QuantityBreak1 { get; set; }

    public decimal QuantityBreak2 { get; set; }

    public decimal QuantityBreak3 { get; set; }

    public decimal QuantityBreak4 { get; set; }

    public decimal QuantityBreak5 { get; set; }

    public decimal QuantityBreak6 { get; set; }

    public decimal QuantityBreak7 { get; set; }

    public decimal QuantityBreak8 { get; set; }

    public int SequenceNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User3 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User4 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string User5 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Warehouse { get; set; }
}