
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Prophet21.V2017.Middleware.Models.Entities;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ArrayOfContact", Namespace = "")]
public class ArrayOfContact
{
    [System.Xml.Serialization.XmlElement("Contact")]
    public List<Contact> Contacts { get; set; } = new List<Contact>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Contact", Namespace = "")]
public class Contact
{
    public List<ContactLink> ContactLinks { get; set; } = new List<ContactLink>();

    public string Salutation { get; set; }

    public string FirstName { get; set; }

    public string Mi { get; set; }

    public string LastName { get; set; }

    public string Title { get; set; }

    public string AddressId { get; set; }

    public string Mailstop { get; set; }

    public string NoOfCycleDays { get; set; }

    public string Comments { get; set; }

    public string DirectPhone { get; set; }

    public string PhoneExt { get; set; }

    public string DirectFax { get; set; }

    public string FaxExt { get; set; }

    public string Beeper { get; set; }

    public string Cellular { get; set; }

    public string Class1id { get; set; }

    public string Class2id { get; set; }

    public string Class3id { get; set; }

    public string Class4id { get; set; }

    public string Class5id { get; set; }

    public string HomeAddress1 { get; set; }

    public string HomeAddress2 { get; set; }

    public string HomePhone { get; set; }

    public string HomeFax { get; set; }

    public string HomeEmailAddress { get; set; }

    public string Birthday { get; set; }

    public string Anniversary { get; set; }

    public string EmailAddress { get; set; }

    public string Url { get; set; }

    public string CellularExt { get; set; }

    public string Id { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ContactLink", Namespace = "")]
public class ContactLink
{
    public string ContactLinkId { get; set; }

    public string ContactType { get; set; }

    public string CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string ContactLinkName { get; set; }

    public string Status { get; set; }

    public string ContactId { get; set; }

    public string Delete { get; set; }
}