
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.APlus.V10.CommerceGateway.Models.CreateOrder;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
public class CreateOrderRequest
{
    public List<RequestOrder> Orders { get; set; } = new List<RequestOrder>();

    [System.Xml.Serialization.XmlAttributeAttribute]
    public string Name { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Order", Namespace = "")]
public class RequestOrder
{
    public RequestOrderHeader OrderHeader { get; set; }

    public RequestOrderDetail OrderDetail { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderHeader", Namespace = "")]
public class RequestOrderHeader
{
    public string WebTransactionType { get; set; }

    public string CCCustomerID { get; set; }

    public string CCCreditCardNbr { get; set; }

    public string CCPaymentType { get; set; }

    public string CCCreditCardExp { get; set; }

    public string CCCardHolder { get; set; }

    public string CCCVV2 { get; set; }

    public string CCAddr1 { get; set; }

    public string CCAddr2 { get; set; }

    public string CCAddr3 { get; set; }

    public string CCAddr4 { get; set; }

    public string CCCity { get; set; }

    public string CCState { get; set; }

    public string CCZip { get; set; }

    public string CCCountry { get; set; }

    public string CCPONumber { get; set; }

    public string CCShipToZip { get; set; }

    public string CCTaxAmount { get; set; }

    public string CCAuthorizationAmount { get; set; }

    public string CCEND { get; set; }

    public string CustomerID { get; set; }

    public string AuthorizationAmount { get; set; }

    public string CreditCardNbr { get; set; }

    public string PaymentType { get; set; }

    public string CreditCardExp { get; set; }

    public string WarehouseId { get; set; }

    public string OrderSource { get; set; }

    public string ReviewOrderHold { get; set; }

    public string PONumber { get; set; }

    public string WorkStation { get; set; }

    public string BillToContact { get; set; }

    public string BillToCity { get; set; }

    public string BillToState { get; set; }

    public string BillToZip { get; set; }

    public string BillToPhone { get; set; }

    public string BillToPhoneExt { get; set; }

    public string BillToCntryCode { get; set; }

    public string CarrierCode { get; set; }

    public string CustomerAddr1 { get; set; }

    public string CustomerAddr2 { get; set; }

    public string CustomerAddr3 { get; set; }

    public string CustomerAddr4 { get; set; }

    public string ContractNumber { get; set; }

    public string CustomerName { get; set; }

    public string CustomerCountry { get; set; }

    public string TaxExemptCentury { get; set; }

    public string TaxExemptDate { get; set; }

    public string TaxExCertNumber { get; set; }

    public string FOBCode { get; set; }

    public string ReqShipDate { get; set; }

    public string ShipToAddr1 { get; set; }

    public string ShipToAddr2 { get; set; }

    public string ShipToAddr3 { get; set; }

    public string ShipToAddr4 { get; set; }

    public string ShipToContact { get; set; }

    public string ShipToCity { get; set; }

    public string ShipToCountry { get; set; }

    public string ShipToName { get; set; }

    public string ShipToNumber { get; set; }

    public string ShipToState { get; set; }

    public string ShipToPhone { get; set; }

    public string ShipToPhoneExt { get; set; }

    public string ShipToCntryCode { get; set; }

    public string ShipToZip { get; set; }

    public string WebUserID { get; set; }

    public string WebProcessID { get; set; }

    public string WebTransactionID { get; set; }

    public string WebOrderID { get; set; }

    public string FreightMethod { get; set; }

    public string OrderType { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderDetail", Namespace = "")]
public class RequestOrderDetail
{
    [System.Xml.Serialization.XmlElement("LineItemInfo")]
    public List<RequestLineItemInfo> LineItemInfo { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "LineItemInfo", Namespace = "")]
public class RequestLineItemInfo
{
    public string ItemNumber { get; set; }

    public string OrderQty { get; set; }

    public string UnitOfMeasure { get; set; }

    public string WarehouseId { get; set; }

    public string LineItemType { get; set; }

    public string OverridePrice { get; set; }

    public string ItemDesc1 { get; set; }

    public string ItemDesc2 { get; set; }

    public string ActualSellPrice { get; set; }

    public string Cost { get; set; }

    public string NonStockFlag { get; set; }

    public string ChargeType { get; set; }

    public string DropShip { get; set; }

    public string DueDate { get; set; }

    public string ExtendedWeight { get; set; }

    public string ListPrice { get; set; }

    public string ItemId { get; set; }
}