
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.APlus.V10.CommerceGateway.Models.CreateOrder;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Order", Namespace = "")]
public class CreateOrderResponse
{
    public ResponseOrderHeader OrderHeader { get; set; }

    public ResponseOrderDetail OrderDetail { get; set; }

    public ResponseOrderTotal OrderTotal { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderHeader", Namespace = "")]
public class ResponseOrderHeader
{
    public string Message { get; set; }

    public string CompletionCode { get; set; }

    public string OrderNumber { get; set; }

    public string OrderGeneration { get; set; }

    public string PONumber { get; set; }

    public string InvoiceAmount { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderDetail", Namespace = "")]
public class ResponseOrderDetail
{
    [System.Xml.Serialization.XmlElement("LineItemInfo")]
    public List<ResponseLineItemInfo> LineItemInfo { get; set; } = new List<ResponseLineItemInfo>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "LineItemInfo", Namespace = "")]
public class ResponseLineItemInfo
{
    public string ItemNumber { get; set; }

    public string Description { get; set; }

    public string OrderQty { get; set; }

    public string ShipQty { get; set; }

    public string BackOrdQty { get; set; }

    public string ActualSellPrice { get; set; }

    public string LineAmount { get; set; }

    public string UnitOfMeasure { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderTotal", Namespace = "")]
public class ResponseOrderTotal
{
    public string SalesAmount { get; set; }

    public string TotalSpecialCharge { get; set; }

    public string TradeDiscountAmount { get; set; }

    public string SalesTaxAmount { get; set; }

    public string FederalExciseAmount { get; set; }

    public string TotContnChrg { get; set; }

    public string TotalOrderValue { get; set; }

    public string TotalInvoiceAmount { get; set; }

    public string CurrencyCode { get; set; }

    public string AmtAuthCC { get; set; }

    public string Done { get; set; }

    public string TotalOrderWeight { get; set; }
}