
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V11.IonApi.Models.SFOEOrderTotLoadV4;

using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

[System.SerializableAttribute]
public class SFOEOrderTotLoadV4Response
{
    [JsonProperty("response")]
    public Response Response { get; set; }
}

[System.SerializableAttribute]
public class Response
{
    [JsonProperty("cErrorMessage")]
    public string ErrorMessage { get; set; }

    [JsonProperty("tOrdloadhdrdata")]
    public OrdLoadHdrDataCollection OrdLoadHdrDataCollection { get; set; }

    [JsonProperty("tOrdloadlinedata")]
    public OrdLoadLineDataCollection OrdLoadLineDataCollection { get; set; }

    [JsonProperty("tOrdtotdata")]
    public OrdTotDataCollection OrdTotDataCollection { get; set; }

    [JsonProperty("tOrdtotextamt")]
    public OrdTotExtAmtCollection OrdTotExtAmtCollection { get; set; }

    [JsonProperty("tOutfieldvalue")]
    public OutFieldValueCollection OutFieldValueCollection { get; set; }

    [JsonProperty("tOrdloadhdrfreight")]
    public OrdLoadHdrFreightCollection OrdLoadHdrFreightCollection { get; set; }
}

[System.SerializableAttribute]
public class OrdLoadHdrDataCollection
{
    [JsonProperty("t-ordloadhdrdata")]
    public List<OrdLoadHdrData> OrdLoadHdrDatas { get; set; } = new List<OrdLoadHdrData>();
}

[System.SerializableAttribute]
public class OrdLoadHdrData
{
    public string Messageout { get; set; }

    public int Orderno { get; set; }

    public int Ordersuf { get; set; }

    public string Completioncd { get; set; }

    public string Custpo { get; set; }

    public decimal Totinvamt { get; set; }
}

[System.SerializableAttribute]
public class OrdLoadLineDataCollection
{
    [JsonProperty("t-ordloadlinedata")]
    public List<OrdLoadLineData> OrdLoadLineDatas { get; set; } = new List<OrdLoadLineData>();
}

[System.SerializableAttribute]
public class OrdLoadLineData
{
    public int Orderno { get; set; }

    public int Ordersuf { get; set; }

    public int Lineno { get; set; }

    public string Shipprod { get; set; }

    public string Descrip { get; set; }

    public decimal Qtyord { get; set; }

    public decimal Qtyship { get; set; }

    public decimal Qtybo { get; set; }

    public decimal Price { get; set; }

    public decimal Netamt { get; set; }

    public string Unit { get; set; }
}

[System.SerializableAttribute]
public class OrdTotDataCollection
{
    [JsonProperty("t-ordtotdata")]
    public List<OrdTotData> OrdTotDatas { get; set; } = new List<OrdTotData>();
}

[System.SerializableAttribute]
public class OrdTotData
{
    public string Messageout { get; set; }

    public decimal Totlineamt { get; set; }

    public decimal Totaddonamt { get; set; }

    public decimal Totdiscamt { get; set; }

    public decimal Tottaxamt { get; set; }

    public decimal Totexciseamt { get; set; }

    public decimal Totcontaineramt { get; set; }

    public decimal Totordamt { get; set; }

    public decimal Totinvamt { get; set; }

    public string Currencyty { get; set; }

    public decimal Ccauthamt { get; set; }

    public string Completioncd { get; set; }

    public decimal Totweight { get; set; }
}

[System.SerializableAttribute]
public class OrdTotExtAmtCollection
{
    [JsonProperty("t-ordtotextamt")]
    public List<OrdTotExtAmt> OrdTotExtAmts { get; set; } = new List<OrdTotExtAmt>();
}

[System.SerializableAttribute]
public class OrdTotExtAmt
{
    public int Seqno { get; set; }

    public string Descrip { get; set; }

    public decimal Amount { get; set; }

    public string Type { get; set; }
}

[System.SerializableAttribute]
public class OutFieldValueCollection
{
    [JsonProperty("t-outfieldvalue")]
    public List<OutFieldValue> OutFieldValues { get; set; } = new List<OutFieldValue>();
}

[System.SerializableAttribute]
public class OutFieldValue
{
    public string Level { get; set; }

    public int Lineno { get; set; }

    public int Seqno { get; set; }

    public string Fieldname { get; set; }

    public string Fieldvalue { get; set; }
}

[System.SerializableAttribute]
public class OrdLoadHdrFreightCollection
{
    [JsonProperty("t-ordloadhdrfreight")]
    public List<OrdLoadHdrFreight> OrdLoadHdrFreights { get; set; } = new List<OrdLoadHdrFreight>();
}

[System.SerializableAttribute]
public class OrdLoadHdrFreight
{
    public int Cono { get; set; }

    public string Whse { get; set; }

    public string Shipvia { get; set; }

    public string Shipviadesc { get; set; }

    public string Zone { get; set; }

    public decimal Overmaxrate { get; set; }

    public decimal OSrderwghtlim { get; set; }

    public decimal Shipwghtlim { get; set; }

    public decimal Orderwght { get; set; }

    public decimal Shipwght { get; set; }

    public decimal Orderfrt { get; set; }

    public decimal Shipfrt { get; set; }

    public decimal Ordfrtextra1 { get; set; }

    public decimal Ordfrtextra2 { get; set; }

    public decimal Shipfrtextra1 { get; set; }

    public decimal Shipfrtextra2 { get; set; }

    public decimal Calcorderfrt { get; set; }

    public decimal Addonwithoutfrt { get; set; }

    public decimal Totinvamt { get; set; }
}