
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V11.IonApi.Models.SFOEOrderTotLoadV4;

using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;

[System.SerializableAttribute]
public class SFOEOrderTotLoadV4Request
{
    [JsonProperty("request")]
    public Request Request { get; set; }
}

[System.SerializableAttribute]
public class Request : IRequest
{
    public int CompanyNumber { get; set; }

    public string OperatorInit { get; set; }

    public string OperatorPassword { get; set; }

    [JsonProperty("tInputccdata")]
    public InputCreditCardDataCollection InputCreditCardDataCollection { get; set; } = new InputCreditCardDataCollection();

    [JsonProperty("tInputheaderdata")]
    public InputHeaderDataCollection InputHeaderDataCollection { get; set; } = new InputHeaderDataCollection();

    [JsonProperty("tInputlinedata")]
    public InputLineDataCollection InputLineDataCollection { get; set; } = new InputLineDataCollection();

    [JsonProperty("tInputheaderextradata")]
    public InputHeaderExtraDataCollection InputHeaderExtraDataCollection { get; set; } = new InputHeaderExtraDataCollection();

    [JsonProperty("tInputlineextradata")]
    public InputLineExtraDataCollection InputLineExtraDataCollection { get; set; } = new InputLineExtraDataCollection();

    [JsonProperty("tInfieldvalue")]
    public InFieldValueCollection InFieldValueCollection { get; set; } = new InFieldValueCollection();
}

[System.SerializableAttribute]
public class InputCreditCardDataCollection
{
    [JsonProperty("t-inputccdata")]
    public List<InputCreditCardData> InputCreditCardDatas { get; set; } = new List<InputCreditCardData>();
}

[System.SerializableAttribute]
public class InputCreditCardData
{
    public string Cccustomerid { get; set; }

    public string Cccreditcardnbr { get; set; }

    public string Ccpaymenttype { get; set; }

    public string Cccreditcardexp { get; set; }

    public string Cccardholder { get; set; }

    public string Cccvv2 { get; set; }

    public string Ccaddr1 { get; set; }

    public string Ccaddr2 { get; set; }

    public string Ccaddr3 { get; set; }

    public string Ccaddr4 { get; set; }

    public string Cccity { get; set; }

    public string Ccstate { get; set; }

    public string Cczip { get; set; }

    public string Cccountry { get; set; }

    public string Ccponumber { get; set; }

    public string Ccshiptozip { get; set; }

    public decimal Cctaxamount { get; set; }

    public decimal Ccauthorizationamount { get; set; }
}

[System.SerializableAttribute]
public class InputHeaderDataCollection
{
    [JsonProperty("t-inputheaderdata")]
    public List<InputHeaderData> InputHeaderDatas { get; set; } = new List<InputHeaderData>();
}

[System.SerializableAttribute]
public class InputHeaderData
{
    public decimal Taxamount { get; set; }

    public decimal Authorizationamount { get; set; }

    public string Customerid { get; set; }

    public string Creditcardnbr { get; set; }

    public string Paymenttype { get; set; }

    public string Creditcardexp { get; set; }

    public string Warehouseid { get; set; }

    public string Ordersource { get; set; }

    public string Revieworderhold { get; set; }

    public string Ponumber { get; set; }

    public string Ordnumber { get; set; }

    public string Workstation { get; set; }

    public string Billtocontact { get; set; }

    public string Billtocity { get; set; }

    public string Billtostate { get; set; }

    public string Billtozip { get; set; }

    public string Billtophone { get; set; }

    public string Billtophoneext { get; set; }

    public string Carriercode { get; set; }

    public string Customeraddr1 { get; set; }

    public string Customeraddr2 { get; set; }

    public string Customeraddr3 { get; set; }

    public string Customeraddr4 { get; set; }

    public string Contractnumber { get; set; }

    public string Customername { get; set; }

    public string Customercountry { get; set; }

    public string Taxexemptcentury { get; set; }

    public string Taxexemptdate { get; set; }

    public string Taxexcertnumber { get; set; }

    public string Fobcode { get; set; }

    public string Reqshipdate { get; set; }

    public string Shiptoaddr1 { get; set; }

    public string Shiptoaddr2 { get; set; }

    public string Shiptoaddr3 { get; set; }

    public string Shiptoaddr4 { get; set; }

    public string Shiptocontact { get; set; }

    public string Shiptocity { get; set; }

    public string Shiptocountry { get; set; }

    public string Shiptoname { get; set; }

    public string Shiptonumber { get; set; }

    public string Shiptostate { get; set; }

    public string Shiptophone { get; set; }

    public string Shiptophoneext { get; set; }

    public string Shiptozip { get; set; }

    public string Webtransactiontype { get; set; }

    public string Webprocessid { get; set; }

    public string Webtransactionid { get; set; }

    public string Weborderid { get; set; }

    public string Freightmethod { get; set; }

    public string Ordertype { get; set; }

    public string Quotereviewdate { get; set; }
}

[System.SerializableAttribute]
public class InputLineDataCollection
{
    [JsonProperty("t-inputlinedata")]
    public List<InputLineData> InputLineDatas { get; set; } = new List<InputLineData>();
}

[System.SerializableAttribute]
public class InputLineData
{
    public string Itemnumber { get; set; }

    public decimal Orderqty { get; set; }

    public string Unitofmeasure { get; set; }

    public string Warehouseid { get; set; }

    public string Lineitemtype { get; set; }

    public string Itemdesc1 { get; set; }

    public string Itemdesc2 { get; set; }

    public decimal Actualsellprice { get; set; }

    public decimal Cost { get; set; }

    public string Nonstockflag { get; set; }

    public string Chargetype { get; set; }

    public string Dropship { get; set; }

    public string Duedate { get; set; }

    public decimal Extendedweight { get; set; }

    public string Listprice { get; set; }

    public int Itemid { get; set; }

    public int Seqno { get; set; }

    public string Shipinstrty { get; set; }
}

[System.SerializableAttribute]
public class InputHeaderExtraDataCollection
{
    [JsonProperty("t-inputheaderextradata")]
    public List<InputHeaderExtraData> InputHeaderExtraDatas { get; set; } = new List<InputHeaderExtraData>();
}

[System.SerializableAttribute]
public class InputHeaderExtraData
{
    public string Fieldname { get; set; }

    public string Fieldvalue { get; set; }

    public int Seqno { get; set; }
}

[System.SerializableAttribute]
public class InputLineExtraDataCollection
{
    [JsonProperty("t-inputlineextradata")]
    public List<InputLineExtraData> InputLineExtraDatas { get; set; } = new List<InputLineExtraData>();
}

[System.SerializableAttribute]
public class InputLineExtraData
{
    public string Fieldname { get; set; }

    public string Fieldvalue { get; set; }

    public int Lineidentifier { get; set; }

    public int Seqno { get; set; }
}

[System.SerializableAttribute]
public class InFieldValueCollection
{
    [JsonProperty("t-infieldvalue")]
    public List<InFieldValue> InFieldValues { get; set; } = new List<InFieldValue>();
}

[System.SerializableAttribute]
public class InFieldValue
{
    public string Level { get; set; }

    public int Lineno { get; set; }

    public int Seqno { get; set; }

    public string Fieldname { get; set; }

    public string Fieldvalue { get; set; }
}