// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Facts.V9.Api.Models.PriceAvailability
{
    using System.Collections.Generic;

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "RequestBatch", Namespace = "")]
    public class PriceAvailabilityRequest : IRequest
    {
        public Request Request { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string ConsumerKey { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string DateTime { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Language { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Password { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string SerialID { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
    public class Request
    {
        public string CustomerNumber { get; set; }

        public bool DefaultWarehouseOnly { get; set; }

        public List<RequestItem> Items { get; set; } = new List<RequestItem>();

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Company { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string RequestID { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string SerialID { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Item", Namespace = "")]
    public class RequestItem
    {
        public bool CalculatePrices { get; set; }

        public string ItemNumber { get; set; }

        public bool NonStockFlag { get; set; }

        public decimal OrderQuantity { get; set; }

        public string ShipToNumber { get; set; }

        public string UnitOfMeasure { get; set; }

        public string WarehouseID { get; set; }

        public string ConfigHeaderId { get; set; }

        public string ConfigLineId { get; set; }
    }
}
