// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Facts.V9.Api.Models.OrderLoad
{
    using System.Collections.Generic;

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "RequestBatch", Namespace = "")]
    public class OrderLoadRequest : IRequest
    {
        public Request Request { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string ConsumerKey { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string DateTime { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Language { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Password { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string SerialID { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
    public class Request
    {
        public List<RequestOrder> Orders { get; set; } = new List<RequestOrder>();

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Company { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string RequestID { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string SerialID { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Order", Namespace = "")]
    public class RequestOrder
    {
        public OrderHeader OrderHeader { get; set; }

        public List<LineItemInfo> OrderDetail { get; set; } = new List<LineItemInfo>();
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderHeader", Namespace = "")]
    public class OrderHeader
    {
        public string BillToCity { get; set; }

        public string BillToCntryCode { get; set; }

        public string BillToContact { get; set; }

        public string BillToPhone { get; set; }

        public string BillToPhoneExt { get; set; }

        public string BillToState { get; set; }

        public string BillToZipCode { get; set; }

        public string CarrierCode { get; set; }

        public string ContractNumber { get; set; }

        public string CustomerAddress1 { get; set; }

        public string CustomerAddress2 { get; set; }

        public string CustomerAddress3 { get; set; }

        public string CustomerAddress4 { get; set; }

        public string CustomerCountry { get; set; }

        public string CustomerName { get; set; }

        public string CustomerNumber { get; set; }

        public string FobCode { get; set; }

        public decimal FreightAmount { get; set; }

        public string FreightMethod { get; set; }

        public decimal HandlingAmount { get; set; }

        public string OrderSource { get; set; }

        public string OrderType { get; set; }

        public string OrdNumber { get; set; }

        public string PoNumber { get; set; }

        public string QuoteReviewDate { get; set; }

        public string RequestedShipDate { get; set; }

        public string ReviewOrderHold { get; set; }

        public string ShipToAddress1 { get; set; }

        public string ShipToAddress2 { get; set; }

        public string ShipToAddress3 { get; set; }

        public string ShipToAddress4 { get; set; }

        public string ShipToCity { get; set; }

        public string ShipToCntryCode { get; set; }

        public string ShipToContact { get; set; }

        public string ShipToCountry { get; set; }

        public string ShipToName { get; set; }

        public string ShipToNumber { get; set; }

        public string ShipToPhone { get; set; }

        public string ShipToPhoneExt { get; set; }

        public string ShipToState { get; set; }

        public string ShipToZipCode { get; set; }

        public string TaxExCertNumber { get; set; }

        public string TaxExemptCentury { get; set; }

        public string TaxExemptDate { get; set; }

        public string WarehouseID { get; set; }

        public string WebOrderID { get; set; }

        public string WebProcessID { get; set; }

        public string WebTransactionID { get; set; }

        public string WebTransactionType { get; set; }

        public string WebUserID { get; set; }

        public string WorkStation { get; set; }

        public bool IsIncludeFreight { get; set; }

        public bool IsPickUpOrder { get; set; }

        public string Address1 { get; set; }

        public string Address2 { get; set; }

        public string Address3 { get; set; }

        public string Address4 { get; set; }

        public decimal AuthorizationAmount { get; set; }

        public string CardHolder { get; set; }

        public string CCRefNum { get; set; }

        public string CCAuthNum { get; set; }

        public string CCMaskedNum { get; set; }

        public string CCType { get; set; }

        public string CCMerchantID { get; set; }

        public string CCProcessorID { get; set; }

        public string City { get; set; }

        public string Country { get; set; }

        public string CreditCardExpiration { get; set; }

        public string CreditCardNumber { get; set; }

        public string Cvv2 { get; set; }

        public string PaymentType { get; set; }

        public string State { get; set; }

        public decimal TaxAmount { get; set; }

        public string ZipCode { get; set; }

        public bool CreditCardInfoEncrypted { get; set; }

        public string APIEncryptVersion { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LineItemInfo", Namespace = "")]
    public class LineItemInfo
    {
        public decimal ActualSellPrice { get; set; }

        public string ChargeType { get; set; }

        public decimal Cost { get; set; }

        public string DropShip { get; set; }

        public string DueDate { get; set; }

        public decimal ExtendedWeight { get; set; }

        public string ItemDescription1 { get; set; }

        public string ItemDescription2 { get; set; }

        public string ItemID { get; set; }

        public string ItemNumber { get; set; }

        public string LineItemType { get; set; }

        public string ListPrice { get; set; }

        public bool NonStockFlag { get; set; }

        public decimal OrderQty { get; set; }

        public int SequenceNumber { get; set; }

        public bool ShipInstructionType { get; set; }

        public string UnitOfMeasure { get; set; }

        public string WarehouseID { get; set; }
    }
}
