
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Prophet21.V2017.Middleware.Models.GetItemPrice;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "GetItemPrice", Namespace = "")]
public class GetItemPrice
{
    public Request Request { get; set; }

    public Reply Reply { get; set; }

    public ReplyStatus ReplyStatus { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
public class Request
{
    public RequestB2BSellerVersion B2BSellerVersion { get; set; }

    public string CustomerCode { get; set; }

    public string StoreName { get; set; }

    public string WebReferenceNumber { get; set; }

    public string LocationID { get; set; }

    public string GetCostType { get; set; }

    public string GetCompanyAvailability { get; set; }

    public string GetRemainingFreeQuantity { get; set; }

    public string GetWebDescription { get; set; }

    public string GetExtendedDescription { get; set; }

    public string GetAvailabilityOnly { get; set; }

    public string ContractUID { get; set; }

    public string ShipToID { get; set; }

    public string GetProductionOrderInfo { get; set; }

    public string GetPriceBreaks { get; set; }

    public List<RequestItem> ListOfItems { get; set; } = new List<RequestItem>();

    public string UseSystemSettingForPricingUnit { get; set; }

    [System.Xml.Serialization.XmlElement("SourceLocations")]
    public RequestSourceLocations SourceLocations { get; set; }

    public string AllCompaniesWideAvailability { get; set; }

    public string GetListOfItemLocationQuantities { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "B2BSellerVersion", Namespace = "Request")]
public class RequestB2BSellerVersion
{
    public string MajorVersion { get; set; }

    public string MinorVersion { get; set; }

    public string BuildNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Item", Namespace = "Request")]
public class RequestItem
{
    public string ItemID { get; set; }

    public string CustomerPartNumber { get; set; }

    public string Quantity { get; set; }

    public string UnitName { get; set; }

    public string UnitSize { get; set; }

    public string InvMastUID { get; set; }

    public string DefaultPricingUOM { get; set; }

    public string DefaultPricingUnitSize { get; set; }

    public string Combinable { get; set; }

    public string NetPrice { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SourceLocations", Namespace = "Request")]
public class RequestSourceLocations
{
    public string IncludeExclude { get; set; }

    public List<RequestLocation> ListOfLocations { get; set; } = new List<RequestLocation>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Location", Namespace = "Request")]
public class RequestLocation
{
    public string LocID { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Reply", Namespace = "")]
public class Reply
{
    public List<ReplyItem> ListOfItems { get; set; } = new List<ReplyItem>();

    public int RowCount { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Item", Namespace = "")]
public class ReplyItem
{
    public string ItemID { get; set; }

    public string LocationName { get; set; }

    public string LeadTimeDays { get; set; }

    public string FreeQuantity { get; set; }

    public string QuantityInTransit { get; set; }

    public string Quantity { get; set; }

    public string UnitName { get; set; }

    public string UnitSize { get; set; }

    public string CustomerPartNumber { get; set; }

    public string NetPrice { get; set; }

    public string DoNotAutoAllocateDesc { get; set; }

    public string WebDescription { get; set; }

    public string ExtendedDescription { get; set; }

    public string BreakID { get; set; }

    public string PricedByContract { get; set; }

    public string ProductionOrderQtyToMake { get; set; }

    public string UnitCost { get; set; }

    public string PricingUOM { get; set; }

    public string PricingUnitSize { get; set; }

    public List<ReplyBreak> ListOfBreaks { get; set; } = new List<ReplyBreak>();

    public string GetPriceBreaks { get; set; }

    public string InvMastUID { get; set; }

    public string DefaultPricingUOM { get; set; }

    public string DefaultPricingUnitSize { get; set; }

    public string Combinable { get; set; }

    public string RemainingFreeQuantity { get; set; }

    public List<ReplyItemLocationQuantity> ListOfItemLocationQuantities { get; set; } = new List<ReplyItemLocationQuantity>();

    public string ListPrice { get; set; }

    public string Discontinued { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Break", Namespace = "")]
public class ReplyBreak
{
    public string Minimum { get; set; }

    public string Maximum { get; set; }

    public string NetPrice { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ItemLocationQuantity", Namespace = "")]
public class ReplyItemLocationQuantity
{
    public string LocationID { get; set; }

    public string FreeQuantity { get; set; }

    public string LeadTimeDays { get; set; }

    public string QtyOnBackorder { get; set; }

    public string QtyOnPO { get; set; }

    public string QuantityInTransit { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ReplyStatus", Namespace = "")]
public class ReplyStatus
{
    public int Result { get; set; }

    public string Message { get; set; }
}