
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V11.IonApi.Models.ARCustomerMnt;

using System.Collections.Generic;
using Newtonsoft.Json;

[System.SerializableAttribute]
public class ARCustomerMntRequest
{
    [JsonProperty("request")]
    public Request Request { get; set; }
}

[System.SerializableAttribute]
public class Request : IRequest
{
    public int CompanyNumber { get; set; }

    public string OperatorInit { get; set; }

    public string OperatorPassword { get; set; }

    [JsonProperty("tMntTt")]
    public InFieldModificationCollection InFieldModificationCollection { get; set; } = new InFieldModificationCollection();

    public string ExtraData { get; set; }
}

[System.SerializableAttribute]
public class InFieldModificationCollection
{
    [JsonProperty("t-mnt-tt")]
    public List<InFieldModification> InFieldModifications { get; set; } = new List<InFieldModification>();
}

[System.SerializableAttribute]
public class InFieldModification
{
    public int SetNo { get; set; }

    public int SeqNo { get; set; }

    public string Key1 { get; set; }

    public string Key2 { get; set; }

    public string UpdateMode { get; set; }

    public string FieldName { get; set; }

    public string FieldValue { get; set; }
}