
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V61.SXApi.Models.OEPricingMultipleV3;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "Nxtrend.WS")]
public class OEPricingMultipleV3Request
{
    public decimal customerNumber { get; set; }

    public string ediPartnerCode { get; set; }

    public string shipTo { get; set; }

    public string keyCode { get; set; }

    public bool getPriceBreaks { get; set; }

    public bool useDefaultWhse { get; set; }

    public bool sendFullQtyOnOrder { get; set; }

    public bool checkOtherWhseInventory { get; set; }

    public string pricingMethod { get; set; }

    public string extraData { get; set; }

    public List<OEPricingMultipleV3inputProduct> arrayProduct { get; set; } = new List<OEPricingMultipleV3inputProduct>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OEPricingMultipleV3.input.Product", Namespace = "Nxtrend.WS")]
public class OEPricingMultipleV3inputProduct
{
    public int sequenceNumber { get; set; }

    public string warehouse { get; set; }

    public string productCode { get; set; }

    public string operatorChannel { get; set; }

    public decimal quantity { get; set; }

    public string unitOfMeasure { get; set; }

    public string user1 { get; set; }

    public string user2 { get; set; }

    public string user3 { get; set; }

    public string user4 { get; set; }

    public string user5 { get; set; }
}