
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V61.SXApi.Models.OEPricingMultipleV3;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "Nxtrend.WS")]
public class OEPricingMultipleV3Response
{
    public string errorMessage { get; set; }

    public List<OEPricingMultipleV3outputPrice> arrayPrice { get; set; } = new List<OEPricingMultipleV3outputPrice>();

    public List<OEPricingMultipleV3outputPricebreak> arrayPricebreak { get; set; } = new List<OEPricingMultipleV3outputPricebreak>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OEPricingMultipleV3.output.Price", Namespace = "Nxtrend.WS")]
public class OEPricingMultipleV3outputPrice
{
    public int sequenceNumber { get; set; }

    public string warehouse { get; set; }

    public string productCode { get; set; }

    public decimal quantity { get; set; }

    public decimal stockingQuantity { get; set; }

    public string unitOfMeasure { get; set; }

    public decimal unitConversion { get; set; }

    public string user1 { get; set; }

    public string user2 { get; set; }

    public string user3 { get; set; }

    public string user4 { get; set; }

    public string user5 { get; set; }

    public string errorMessage { get; set; }

    public decimal price { get; set; }

    public decimal discountAmount { get; set; }

    public string discountType { get; set; }

    public decimal extendedAmount { get; set; }

    public decimal extendedDiscountAmount { get; set; }

    public decimal netAvailable { get; set; }

    public string specialCostType { get; set; }

    public string priceCostPer { get; set; }

    public decimal unitsPerStocking { get; set; }

    public int specialConversion { get; set; }

    public int speicalCostRecordNumber { get; set; }

    public int pricingRecordNumber { get; set; }

    public bool promotionalFlag { get; set; }

    public string priceOriginCode { get; set; }

    public string unitsPerStockingText { get; set; }

    public decimal quantityOnOrder { get; set; }

    public decimal freightAmount { get; set; }

    public bool freightDiscountFlag { get; set; }

    public bool priceBreaksExist { get; set; }

    public decimal spiffAmount { get; set; }

    public bool inventoryInOtherWhse { get; set; }

    public decimal commission { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OEPricingMultipleV3.output.Pricebreak", Namespace = "Nxtrend.WS")]
public class OEPricingMultipleV3outputPricebreak
{
    public int sequenceNumber { get; set; }

    public string warehouse { get; set; }

    public string productCode { get; set; }

    public string user1 { get; set; }

    public string user2 { get; set; }

    public string user3 { get; set; }

    public string user4 { get; set; }

    public string user5 { get; set; }

    public decimal priceBreak1 { get; set; }

    public decimal priceBreak2 { get; set; }

    public decimal priceBreak3 { get; set; }

    public decimal priceBreak4 { get; set; }

    public decimal priceBreak5 { get; set; }

    public decimal priceBreak6 { get; set; }

    public decimal priceBreak7 { get; set; }

    public decimal priceBreak8 { get; set; }

    public decimal priceBreak9 { get; set; }

    public decimal discountPercent1 { get; set; }

    public decimal discountPercent2 { get; set; }

    public decimal discountPercent3 { get; set; }

    public decimal discountPercent4 { get; set; }

    public decimal discountPercent5 { get; set; }

    public decimal discountPercent6 { get; set; }

    public decimal discountPercent7 { get; set; }

    public decimal discountPercent8 { get; set; }

    public decimal discountPercent9 { get; set; }

    public decimal quantityBreak1 { get; set; }

    public decimal quantityBreak2 { get; set; }

    public decimal quantityBreak3 { get; set; }

    public decimal quantityBreak4 { get; set; }

    public decimal quantityBreak5 { get; set; }

    public decimal quantityBreak6 { get; set; }

    public decimal quantityBreak7 { get; set; }

    public decimal quantityBreak8 { get; set; }
}