
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V61.SXApi.Models.SFCustomerSummary;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "Nxtrend.WS")]
public class SFCustomerSummaryResponse
{
    public string errorMessage { get; set; }

    public List<SFCustomerSummaryoutputSummary> arraySummary { get; set; } = new List<SFCustomerSummaryoutputSummary>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SFCustomerSummary.output.Summary", Namespace = "Nxtrend.WS")]
public class SFCustomerSummaryoutputSummary
{
    public string customerName { get; set; }

    public string address1 { get; set; }

    public string address2 { get; set; }

    public string address3 { get; set; }

    public string address4 { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string countryCode { get; set; }

    public string zipCode { get; set; }

    public decimal openOrderAmount { get; set; }

    public decimal billingPeriodAmount { get; set; }

    public decimal agePeriod1Amount { get; set; }

    public decimal agePeriod2Amount { get; set; }

    public decimal agePeriod3Amount { get; set; }

    public decimal agePeriod4Amount { get; set; }

    public decimal amountDue { get; set; }

    public decimal futureAmount { get; set; }

    public decimal salesMonthToDate { get; set; }

    public decimal salesYearToDate { get; set; }

    public decimal salesLastYearYearToDate { get; set; }

    public string dateOfLastPayment { get; set; }

    public string dateOfFirstSale { get; set; }

    public string dateOfLastSale { get; set; }

    public string currencyCode { get; set; }

    public decimal tradeOpenOrderAmount { get; set; }

    public decimal tradeBillingPeriodAmount { get; set; }

    public decimal tradeAgePeriod1Amount { get; set; }

    public decimal tradeAgePeriod2Amount { get; set; }

    public decimal tradeAgePeriod3Amount { get; set; }

    public decimal tradeAgePeriod4Amount { get; set; }

    public decimal tradeAmountDue { get; set; }

    public decimal tradeFutureAmount { get; set; }

    public decimal tradeSalesMonthToDate { get; set; }

    public decimal tradeSalesYearToDate { get; set; }

    public decimal tradeSalesLastYearYearToDate { get; set; }

    public string tradeCurrencyCode { get; set; }

    public string termsDescription { get; set; }

    public decimal ageDaysPeriod1 { get; set; }

    public decimal ageDaysPeriod2 { get; set; }

    public decimal ageDaysPeriod3 { get; set; }

    public decimal ageDaysPeriod4 { get; set; }
}