
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V61.SXApi.Models.ARCustomerMnt;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "Nxtrend.WS")]
public partial class ARCustomerMntResponse
{
    public string errorMessage { get; set; }

    public string returnData { get; set; }
}