
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.APlus.V10.CommerceGateway.Models.LineItemPriceAndAvailability;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
public class LineItemPriceAndAvailabilityRequest
{
    public string TransactionID { get; set; }

    public string RequestID { get; set; }

    public string OrderNumber { get; set; }

    [System.Xml.Serialization.XmlElement("Items")]
    public List<RequestItem> Items { get; set; } = new List<RequestItem>();

    [System.Xml.Serialization.XmlAttributeAttribute]
    public string Name { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Items", Namespace = "")]
public class RequestItem
{
    public string WarehouseID { get; set; }

    public string OrderQuantity { get; set; }

    public string UnitofMeasure { get; set; }

    public string VendorCost { get; set; }

    public string VendorPrice1 { get; set; }

    public string VendorPrice2 { get; set; }

    public string VendorPrice3 { get; set; }

    public string VendorPrice4 { get; set; }

    public string VendorPrice5 { get; set; }

    public string NonStockFlag { get; set; }

    public string CalculatePrices { get; set; }

    public string ShipToNumber { get; set; }

    public string DftWhsOnly { get; set; }

    public string ItemNumber { get; set; }
}