
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.APlus.V10.CommerceGateway.Models.LineItemPriceAndAvailability;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Response", Namespace = "")]
public class LineItemPriceAndAvailabilityResponse
{
    [System.Xml.Serialization.XmlElement("ItemAvailability")]
    public List<ResponseItemAvailability> ItemAvailability { get; set; } = new List<ResponseItemAvailability>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ItemAvailability", Namespace = "")]
public class ResponseItemAvailability
{
    public ResponseTranHeader TranHeader { get; set; }

    public ResponseItem Item { get; set; }

    [System.Xml.Serialization.XmlElement("WarehouseInfo")]
    public List<ResponseWarehouseInfo> WarehouseInfo { get; set; } = new List<ResponseWarehouseInfo>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "TranHeader", Namespace = "")]
public class ResponseTranHeader
{
    public string TransactionID { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Item", Namespace = "")]
public class ResponseItem
{
    public string ItemNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "WarehouseInfo", Namespace = "")]
public class ResponseWarehouseInfo
{
    public string Warehouse { get; set; }

    public string Qty { get; set; }

    public string Price { get; set; }

    public string NextPOQty { get; set; }

    public string NextPODate { get; set; }

    public string ErrorMessage { get; set; }

    public string PricingUOM { get; set; }

    public string PricingUOMPrice { get; set; }

    public string NextQtyBreak { get; set; }

    public string NextQtyPrice { get; set; }

    public string NextBreakType { get; set; }

    public string ExtendedPrice { get; set; }
}