
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Prophet21.V2017.Middleware.Models.GetCartSummary;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "GetCartSummary", Namespace = "")]
public class GetCartSummary
{
    public Request Request { get; set; }

    public Reply Reply { get; set; }

    public ReplyStatus ReplyStatus { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
public class Request
{
    public RequestB2BSellerVersion B2BSellerVersion { get; set; }

    public string StoreName { get; set; }

    public string CustomerCode { get; set; }

    public string PONumber { get; set; }

    public string ShipToID { get; set; }

    public string GetCostType { get; set; }

    public string GetCompanyAvailability { get; set; }

    public string PaymentMethod { get; set; }

    public string ContractUID { get; set; }

    public string WebReferenceNumber { get; set; }

    public string GetProductionOrderInfo { get; set; }

    public string CartRequiredDate { get; set; }

    public string PromoCode { get; set; }

    public string OrderTotalStartDate { get; set; }

    public string OrderTotalEndDate { get; set; }

    public RequestCustomerShipTo CustomerShipTo { get; set; }

    public List<RequestLineItem> ListOfLineItems { get; set; } = new List<RequestLineItem>();

    public List<RequestCoupon> ListOfCoupons { get; set; } = new List<RequestCoupon>();

    public string UseSystemSettingForPricingUnit { get; set; }

    public RequestSourceLocations SourceLocations { get; set; }

    public string AllCompaniesWideAvailability { get; set; }

    public string ProcessMinimumOrderCharge { get; set; }

    public string GetListOfItemLocationQuantities { get; set; }

    public string ListOfOutgoingCarriers { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "B2BSellerVersion", Namespace = "Request")]
public class RequestB2BSellerVersion
{
    public string MajorVersion { get; set; }

    public string MinorVersion { get; set; }

    public string BuildNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "RequestCustomerShipTo", Namespace = "Request")]
public class RequestCustomerShipTo
{
    public RequestShipToAddress ShipToAddress { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ShipToAddress", Namespace = "Request")]
public class RequestShipToAddress
{
    public string ShipToZip { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "LineItem", Namespace = "Request")]
public class RequestLineItem
{
    public string ItemID { get; set; }

    public string CustomerPartNumber { get; set; }

    public string OrderQuantity { get; set; }

    public string UnitName { get; set; }

    public string UnitSize { get; set; }

    public string UnitPrice { get; set; }

    public string SourceLocation { get; set; }

    public string SourceFromAlternateLocations { get; set; }

    public string RequireDate { get; set; }

    public string ContractUID { get; set; }

    public string GetPriceBreaks { get; set; }

    public string NewWebItem { get; set; }

    public string ShoppingCartDetailUID { get; set; }

    public string CalculateTax { get; set; }

    public string InvMastUID { get; set; }

    public string DefaultPricingUOM { get; set; }

    public string DefaultPricingUnitSize { get; set; }

    public string Combinable { get; set; }

    public string CarrierID { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Coupon", Namespace = "Request")]
public class RequestCoupon
{
    public string CouponNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "SourceLocations", Namespace = "Request")]
public class RequestSourceLocations
{
    public string IncludeExclude { get; set; }

    public List<RequestLocation> ListOfLocations { get; set; } = new List<RequestLocation>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Location", Namespace = "Request")]
public class RequestLocation
{
    public string LocID { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Reply", Namespace = "")]
public class Reply
{
    public List<ReplyLineItem> ListOfLineItems { get; set; } = new List<ReplyLineItem>();

    public int RowCount { get; set; }

    public ReplyCartSummary CartSummary { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "LineItem", Namespace = "")]
public class ReplyLineItem
{
    public string ItemID { get; set; }

    public string CustomerPartNumber { get; set; }

    public string OrderQuantity { get; set; }

    public string UnitName { get; set; }

    public string UnitSize { get; set; }

    public string NetPrice { get; set; }

    public string SourceLocation { get; set; }

    public string SourceLocationState { get; set; }

    public string SourceLocationCity { get; set; }

    public string Discount { get; set; }

    public string ExtendedPrice { get; set; }

    public string AllocatedQuantity { get; set; }

    public string BackorderedQuantity { get; set; }

    public string FreeQuantity { get; set; }

    public string LeadTimeDays { get; set; }

    public string Disposition { get; set; }

    public string BreakID { get; set; }

    public string PricedByContract { get; set; }

    public List<ReplyBreak> ListOfBreaks { get; set; } = new List<ReplyBreak>();

    public string NewWebItem { get; set; }

    public string OverBudget { get; set; }

    public string BudgetCd { get; set; }

    public string BudgetDollarLimit { get; set; }

    public string BudgetDollarLimitUsed { get; set; }

    public string BudgetDollarLimitRemaining { get; set; }

    public string ProductionOrderQtyToMake { get; set; }

    public string ItemNotesRequired { get; set; }

    public string UnitCost { get; set; }

    public string PricingUOM { get; set; }

    public string PricingUnitSize { get; set; }

    public string InvMastUID { get; set; }

    public string DefaultPricingUOM { get; set; }

    public string DefaultPricingUnitSize { get; set; }

    public string Combinable { get; set; }

    public string Tax { get; set; }

    public string ShoppingCartDetailUID { get; set; }

    public string RemainingFreeQuantity { get; set; }

    public List<ReplyItemLocationQuantity> ListOfItemLocationQuantities { get; set; } = new List<ReplyItemLocationQuantity>();

    public string MinimumSurchargeItem { get; set; }

    public string MinimumOrderAmount { get; set; }

    public string MinimumGallonAmount { get; set; }

    public string CarrierID { get; set; }

    public string WeeklyTruck { get; set; }

    public string FreightIn { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Break", Namespace = "")]
public class ReplyBreak
{
    public string Minimum { get; set; }

    public string Maximum { get; set; }

    public string NetPrice { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ItemLocationQuantity", Namespace = "")]
public class ReplyItemLocationQuantity
{
    public string LocationID { get; set; }

    public string FreeQuantity { get; set; }

    public string LeadTimeDays { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "CartSummary", Namespace = "")]
public class ReplyCartSummary
{
    public string TotalLineItemAmount { get; set; }

    public string Discounts { get; set; }

    public string Freight { get; set; }

    public string OtherCharges { get; set; }

    public string OtherChargesDescription { get; set; }

    public string SalesTax { get; set; }

    public string OtherTax { get; set; }

    public string TotalInvoiceAmount { get; set; }

    public string RequiredDate { get; set; }

    public List<ReplyFailedItem> ListOfFailedItems { get; set; } = new List<ReplyFailedItem>();

    public string OrderTotal { get; set; }

    public string ListOfOutgoingCarriers { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "FailedItem", Namespace = "")]
public class ReplyFailedItem
{
    public string ItemCode { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorMessage { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ReplyStatus", Namespace = "")]
public class ReplyStatus
{
    public int Result { get; set; }

    public string Message { get; set; }

    public string DebugInfo { get; set; }

    public string PerformanceLogInfo { get; set; }
}