
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Prophet21.V2017.Middleware.Models.OrderImport;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderImport", Namespace = "")]
public class OrderImport
{
    public Request Request { get; set; }

    public Reply Reply { get; set; }

    public ReplyStatus ReplyStatus { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
public class Request
{
    public RequestB2BSellerVersion B2BSellerVersion { get; set; }

    public string CustomerCode { get; set; }

    public string StoreName { get; set; }

    public string WebReferenceNumber { get; set; }

    public string Anonymous { get; set; }

    public string PONumber { get; set; }

    public string NotepadText { get; set; }

    public string NotepadDisplayArea { get; set; }

    public string UseContractAddress { get; set; }

    public string FreightCode { get; set; }

    public string FreightAmount { get; set; }

    public string ContactID { get; set; }

    public string RequireDate { get; set; }

    public string ContractUID { get; set; }

    public string ImportAsQuote { get; set; }

    public string QuoteNumber { get; set; }

    public string WillCall { get; set; }

    public string PackingBasis { get; set; }

    public string BlindShip { get; set; }

    public string UseSystemSettingForPricingUnit { get; set; }

    public RequestCustomerShipTo CustomerShipTo { get; set; }

    public RequestCreditCard CreditCard { get; set; }

    public List<RequestMerchandiseCredit> ListOfMerchandiseCredits { get; set; } = new List<RequestMerchandiseCredit>();

    public List<RequestLineItem> ListOfLineItems { get; set; } = new List<RequestLineItem>();

    public string WebShopperId { get; set; }

    public string WebShopperEmailAddress { get; set; }

    public List<RequestCoupon> ListOfCoupons { get; set; } = new List<RequestCoupon>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "B2BSellerVersion", Namespace = "Request")]
public class RequestB2BSellerVersion
{
    public string MajorVersion { get; set; }

    public string MinorVersion { get; set; }

    public string BuildNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "CustomerShipTo", Namespace = "Request")]
public class RequestCustomerShipTo
{
    public string ShipToID { get; set; }

    public RequestShipToAddress ShipToAddress { get; set; }

    public string ShipToContactFirstName { get; set; }

    public string ShipToContactLastName { get; set; }

    public string ShipToContactSalutation { get; set; }

    public string ShipToContactTitle { get; set; }

    public string ShipToPhone { get; set; }

    public string ShipToFax { get; set; }

    public string ShipToEMail { get; set; }

    public string ShipToCarrierId { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ShipToAddress", Namespace = "Request")]
public class RequestShipToAddress
{
    public string ShipToCompanyName { get; set; }

    public string ShipToAddress1 { get; set; }

    public string ShipToAddress2 { get; set; }

    public string ShipToAddress3 { get; set; }

    public string ShipToCity { get; set; }

    public string ShipToState { get; set; }

    public string ShipToZip { get; set; }

    public string ShipToCountry { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "CreditCard", Namespace = "Request")]
public class RequestCreditCard
{
    public string CV2Number { get; set; }

    public string CardType { get; set; }

    public string AuthorizationCode { get; set; }

    public string CardNumber { get; set; }

    public string ExpirationMonth { get; set; }

    public string ExpirationYear { get; set; }

    public decimal ChargeAmount { get; set; }

    public RequestCardHolder CardHolder { get; set; }

    public string ElementPaymentAccountID { get; set; }

    public string ElementTransactionID { get; set; }

    public string ElementProcessorID { get; set; }

    public string AVSResponseCode { get; set; }

    public string CVVResponseCode { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "CardHolder", Namespace = "Request")]
public class RequestCardHolder
{
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public RequestAddress Address { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Address", Namespace = "Request")]
public class RequestAddress
{
    public string CompanyName { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Country { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "MerchandiseCredit", Namespace = "Request")]
public class RequestMerchandiseCredit
{
    public string MerchandiseCreditNumber { get; set; }

    public string Amount { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "LineItem", Namespace = "Request")]
public class RequestLineItem
{
    public string ItemID { get; set; }

    public string OrderedAs { get; set; }

    public string OrderQuantity { get; set; }

    public string CustomerPartNumber { get; set; }

    public string UnitName { get; set; }

    public string UnitSize { get; set; }

    public string UnitPrice { get; set; }

    public string SourceLocation { get; set; }

    public string RequireDate { get; set; }

    public string ContractUID { get; set; }

    public string NotepadText { get; set; }

    public string NotepadDisplayArea { get; set; }

    public string QuoteLineNumber { get; set; }

    public string QuoteLineComplete { get; set; }

    public string NewWebItem { get; set; }

    public string BinID { get; set; }

    public string Description { get; set; }

    public string ExtendedDescription { get; set; }

    public string SupplierID { get; set; }

    public string CalculateTax { get; set; }

    public string MinimumSurchargeItem { get; set; }

    public string CarrierID { get; set; }

    public string IncomingFreight { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Coupon", Namespace = "Request")]
public class RequestCoupon
{
    public string CouponNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Reply", Namespace = "")]
public class Reply
{
    public string OrderNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "ReplyStatus", Namespace = "")]
public class ReplyStatus
{
    public int Result { get; set; }

    public string Message { get; set; }
}