
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V10.SXApi.Models.SFOEOrderTotLoadV4;

using System.Collections.Generic;

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFOEOrderTotLoadV" + "4")]
public class SFOEOrderTotLoadV4Request
{
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Increditcard3> Increditcard { get; set; } = new List<Increditcard3>();

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Inheaderextradata2> Inheaderextradata { get; set; } = new List<Inheaderextradata2>();

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Ininfieldvalue4> Ininfieldvalue { get; set; } = new List<Ininfieldvalue4>();

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Ininheader3> Ininheader { get; set; } = new List<Ininheader3>();

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Ininline3> Ininline { get; set; } = new List<Ininline3>();

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Inlineextradata2> Inlineextradata { get; set; } = new List<Inlineextradata2>();
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Increditcard", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFOEOrderTotLoadV" + "4")]
public class Increditcard3
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address3 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address4 { get; set; }

    public decimal AuthorizationAmount { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CardHolder { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string City { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Country { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CreditCardExpiration { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CreditCardNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerID { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Cvv2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string PaymentType { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string PoNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToZipCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string State { get; set; }

    public decimal TaxAmount { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ZipCode { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Inheaderextradata", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFOEOrderTotLoadV" + "4")]
public class Inheaderextradata2
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FieldName { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FieldValue { get; set; }

    public int SequenceNumber { get; set; }

    [System.Xml.Serialization.XmlIgnoreAttribute]
    public bool SequenceNumberSpecified { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Ininfieldvalue", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFOEOrderTotLoadV" + "4")]
public class Ininfieldvalue4
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FieldName { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FieldValue { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Level { get; set; }

    public int LineNumber { get; set; }

    public int SequenceNumber { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Ininheader", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFOEOrderTotLoadV" + "4")]
public class Ininheader3
{
    public decimal AuthorizationAmount { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string BillToCity { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string BillToContact { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string BillToPhone { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string BillToPhoneExt { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string BillToState { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string BillToZipCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CarrierCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ContractNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CreditCardExpiration { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CreditCardNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerAddress1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerAddress2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerAddress3 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerAddress4 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerCountry { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerID { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerName { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FobCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FreightMethod { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string OrdNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string OrderSource { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string OrderType { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string PaymentType { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string PoNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string QuoteReviewDate { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string RequestedShipDate { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ReviewOrderHold { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToAddress1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToAddress2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToAddress3 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToAddress4 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToCity { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToContact { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToCountry { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToName { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToPhone { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToPhoneExt { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToState { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipToZipCode { get; set; }

    public decimal TaxAmount { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TaxExCertNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TaxExemptCentury { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TaxExemptDate { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string WarehouseID { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string WebOrderID { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string WebProcessID { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string WebTransactionID { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string WebTransactionType { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string WorkStation { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Ininline", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFOEOrderTotLoadV" + "4")]
public class Ininline3
{
    public decimal ActualSellPrice { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ChargeType { get; set; }

    public decimal Cost { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string DropShip { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string DueDate { get; set; }

    public decimal ExtendedWeight { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ItemDescription1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ItemDescription2 { get; set; }

    public int ItemID { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ItemNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string LineItemType { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ListPrice { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string NonStockFlag { get; set; }

    public decimal OrderQty { get; set; }

    public int SequenceNumber { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ShipInstructionType { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string UnitOfMeasure { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string WarehouseID { get; set; }
}

[System.SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "Inlineextradata", Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFOEOrderTotLoadV" + "4")]
public class Inlineextradata2
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FieldName { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string FieldValue { get; set; }

    public int LineIdentifier { get; set; }

    public int SequenceNumber { get; set; }
}