
// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.SXe.V10.SXApi.Models.SFCustomerSummary;

using System;
using System.Collections.Generic;

[SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFCustomerSummary" + "")]
public class SFCustomerSummaryResponse
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ErrorMessage { get; set; }

    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    public List<Outsummary> Outsummary { get; set; } = new List<Outsummary>();
}

[SerializableAttribute]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/NxT_API.com.infor.sxapi.SFCustomerSummary" + "")]
public class Outsummary
{
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address1 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address2 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address3 { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Address4 { get; set; }

    public decimal AgeDaysPeriod1 { get; set; }

    public decimal AgeDaysPeriod2 { get; set; }

    public decimal AgeDaysPeriod3 { get; set; }

    public decimal AgeDaysPeriod4 { get; set; }

    public decimal AgePeriod1Amount { get; set; }

    public decimal AgePeriod2Amount { get; set; }

    public decimal AgePeriod3Amount { get; set; }

    public decimal AgePeriod4Amount { get; set; }

    public decimal AmountDue { get; set; }

    public decimal BillingPeriodAmount { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string City { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CountryCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CurrencyCode { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string CustomerName { get; set; }

    public DateTime? DateOfFirstSale { get; set; }

    public DateTime? DateOfLastPayment { get; set; }

    public DateTime? DateOfLastSale { get; set; }

    public decimal FutureAmount { get; set; }

    public decimal OpenOrderAmount { get; set; }

    public decimal SalesLastYearYearToDate { get; set; }

    public decimal SalesMonthToDate { get; set; }

    public decimal SalesYearToDate { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string State { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TermsDescription { get; set; }

    public decimal TradeAgePeriod1Amount { get; set; }

    public decimal TradeAgePeriod2Amount { get; set; }

    public decimal TradeAgePeriod3Amount { get; set; }

    public decimal TradeAgePeriod4Amount { get; set; }

    public decimal TradeAmountDue { get; set; }

    public decimal TradeBillingPeriodAmount { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string TradeCurrencyCode { get; set; }

    public decimal TradeFutureAmount { get; set; }

    public decimal TradeOpenOrderAmount { get; set; }

    public decimal TradeSalesLastYearYearToDate { get; set; }

    public decimal TradeSalesMonthToDate { get; set; }

    public decimal TradeSalesYearToDate { get; set; }

    [System.Xml.Serialization.XmlIgnoreAttribute]
    public bool TradeSalesYearToDateSpecified { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ZipCode { get; set; }
}