// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.Facts.V9.Api.Models.OrderTotal
{
    using System.Collections.Generic;

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "RequestBatch", Namespace = "")]
    public class OrderTotalRequest : IRequest
    {
        public Request Request { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string ConsumerKey { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string DateTime { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Language { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Password { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string SerialID { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Request", Namespace = "")]
    public class Request
    {
        public List<RequestOrder> Orders { get; set; } = new List<RequestOrder>();

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string Company { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string RequestID { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute]
        public string SerialID { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Order", Namespace = "")]
    public class RequestOrder
    {
        public OrderHeader OrderHeader { get; set; }

        public List<LineItemInfo> OrderDetail { get; set; } = new List<LineItemInfo>();
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "OrderHeader", Namespace = "")]
    public class OrderHeader
    {
        public string WebTransactionType { get; set; }

        public string CustomerNumber { get; set; }

        public string WarehouseID { get; set; }

        public string ShipToNumber { get; set; }

        public string ShipToName { get; set; }

        public string ShipToAddress1 { get; set; }

        public string ShipToAddress2 { get; set; }

        public string ShipToAddress3 { get; set; }

        public string ShipToAddress4 { get; set; }

        public string ShipToCity { get; set; }

        public string ShipToState { get; set; }

        public string ShipToZipCode { get; set; }

        public string ShipToCountry { get; set; }

        public bool IsPickUpOrder { get; set; }

        public string Address1 { get; set; }

        public string Address2 { get; set; }

        public string Address3 { get; set; }

        public string Address4 { get; set; }

        public string RequestedShipDate { get; set; }
    }

    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "LineItemInfo", Namespace = "")]
    public class LineItemInfo
    {
        public int SequenceNumber { get; set; }

        public string ItemNumber { get; set; }

        public decimal OrderQty { get; set; }

        public string UnitOfMeasure { get; set; }

        public decimal ActualSellPrice { get; set; }

        public string WarehouseID { get; set; }
    }
}
