// <auto-generated>
// This isn't auto-generated, but it keeps stylecop from complaining
// </auto-generated>

namespace Insite.Integration.Connector.CloudSuiteDistribution.V11.IonApi.Models.OePricingMultipleV4
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class OePricingMultipleV4Response
    {
        [JsonProperty("response")]
        public Response Response { get; set; }
    }

    public class Response
    {
        [JsonProperty("cErrorMessage")]
        public string ErrorMessage { get; set; }

        [JsonProperty("tOemultprcoutV2")]
        public PriceOutV2Collection PriceOutV2Collection { get; set; }

        [JsonProperty("tOemultprcoutbrk")]
        public PriceOutBreakCollection PriceOutBreakCollection { get; set; }
    }

    public class PriceOutV2Collection
    {
        [JsonProperty("t-oemultprcoutV2")]
        public List<PriceOutV2> PriceOutV2s { get; set; } = new List<PriceOutV2>();
    }

    public class PriceOutV2
    {
        [JsonProperty("Seqno")]
        public int? SeqNo { get; set; }

        public string Whse { get; set; }

        public string Prod { get; set; }

        [JsonProperty("Qtyord")]
        public decimal? QtyOrd { get; set; }

        [JsonProperty("Stkqtyord")]
        public decimal? StkQtyOrd { get; set; }

        public string Unit { get; set; }

        [JsonProperty("Unitconv")]
        public decimal? UnitConv { get; set; }

        [JsonProperty("Baseprice")]
        public decimal? BasePrice { get; set; }

        [JsonProperty("Listprice")]
        public decimal? ListPrice { get; set; }

        public string Priceonty { get; set; }

        public string User1 { get; set; }

        public string User2 { get; set; }

        public string User3 { get; set; }

        public string User4 { get; set; }

        public string User5 { get; set; }

        [JsonProperty("Errormess")]
        public string ErrorMess { get; set; }

        public decimal? Price { get; set; }

        [JsonProperty("Discamt")]
        public decimal? DiscAmt { get; set; }

        [JsonProperty("Disctype")]
        public string DiscType { get; set; }

        [JsonProperty("Extamt")]
        public decimal? ExtAmt { get; set; }

        [JsonProperty("Extdiscount")]
        public decimal? ExtDiscount { get; set; }

        [JsonProperty("Netavail")]
        public decimal? NetAvail { get; set; }

        public string Vcspeccostty { get; set; }

        public string Vcprccostper { get; set; }

        public decimal? Vccsunperstk { get; set; }

        public int? Vcspecconv { get; set; }

        public int? Vcspecrecno { get; set; }

        [JsonProperty("Pdrecno")]
        public int? PdRecNo { get; set; }

        [JsonProperty("Promofl")]
        public bool? PromoFl { get; set; }

        [JsonProperty("Priceorigcd")]
        public string PriceOrigCd { get; set; }

        public string Cstpertext { get; set; }

        [JsonProperty("Qtyonorder")]
        public decimal? QtyOnOrder { get; set; }

        [JsonProperty("Duedt")]
        public string DueDt { get; set; }

        [JsonProperty("Freightamount")]
        public decimal? FreightAmount { get; set; }

        [JsonProperty("Freightdiscfl")]
        public bool? FreightDiscFl { get; set; }

        [JsonProperty("Qtybreakexistfl")]
        public bool? QtyBreakExistFl { get; set; }

        [JsonProperty("Spiffamount")]
        public decimal? SpiffAmount { get; set; }

        [JsonProperty("Otherwhseinvfl")]
        public bool? OtherWhseInvFl { get; set; }

        public decimal? Commission { get; set; }
    }

    public class PriceOutBreakCollection
    {
        [JsonProperty("t-oemultprcoutbrk")]
        public List<PriceOutBreak> PriceOutBreaks { get; set; } = new List<PriceOutBreak>();
    }

    public class PriceOutBreak
    {
        [JsonProperty("Seqno")]
        public int? SeqNo { get; set; }

        public string Whse { get; set; }

        public string Prod { get; set; }

        public string User1 { get; set; }

        public string User2 { get; set; }

        public string User3 { get; set; }

        public string User4 { get; set; }

        public string User5 { get; set; }

        [JsonProperty("Pricebreak1")]
        public decimal? PriceBreak1 { get; set; }

        [JsonProperty("Pricebreak2")]
        public decimal? PriceBreak2 { get; set; }

        [JsonProperty("Pricebreak3")]
        public decimal? PriceBreak3 { get; set; }

        [JsonProperty("Pricebreak4")]
        public decimal? PriceBreak4 { get; set; }

        [JsonProperty("Pricebreak5")]
        public decimal? PriceBreak5 { get; set; }

        [JsonProperty("Pricebreak6")]
        public decimal? PriceBreak6 { get; set; }

        [JsonProperty("Pricebreak7")]
        public decimal? PriceBreak7 { get; set; }

        [JsonProperty("Pricebreak8")]
        public decimal? PriceBreak8 { get; set; }

        [JsonProperty("Pricebreak9")]
        public decimal? PriceBreak9 { get; set; }

        [JsonProperty("Discountpercent1")]
        public decimal? DiscountPercent1 { get; set; }

        [JsonProperty("Discountpercent2")]
        public decimal? DiscountPercent2 { get; set; }

        [JsonProperty("Discountpercent3")]
        public decimal? DiscountPercent3 { get; set; }

        [JsonProperty("Discountpercent4")]
        public decimal? DiscountPercent4 { get; set; }

        [JsonProperty("Discountpercent5")]
        public decimal? DiscountPercent5 { get; set; }

        [JsonProperty("Discountpercent6")]
        public decimal? DiscountPercent6 { get; set; }

        [JsonProperty("Discountpercent7")]
        public decimal? DiscountPercent7 { get; set; }

        [JsonProperty("Discountpercent8")]
        public decimal? DiscountPercent8 { get; set; }

        [JsonProperty("Discountpercent9")]
        public decimal? DiscountPercent9 { get; set; }

        [JsonProperty("Quantitybreak1")]
        public decimal? QuantityBreak1 { get; set; }

        [JsonProperty("Quantitybreak2")]
        public decimal? QuantityBreak2 { get; set; }

        [JsonProperty("Quantitybreak3")]
        public decimal? QuantityBreak3 { get; set; }

        [JsonProperty("Quantitybreak4")]
        public decimal? QuantityBreak4 { get; set; }

        [JsonProperty("Quantitybreak5")]
        public decimal? QuantityBreak5 { get; set; }

        [JsonProperty("Quantitybreak6")]
        public decimal? QuantityBreak6 { get; set; }

        [JsonProperty("Quantitybreak7")]
        public decimal? QuantityBreak7 { get; set; }

        [JsonProperty("Quantitybreak8")]
        public decimal? QuantityBreak8 { get; set; }
    }
}
